# -*- coding: utf-8 -*-
"""volume_of_sphere.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yo9iS2DJN5kN42EOok9asv4fLfOpxJtk
"""

def calculate_volume_of_sphere(radius):
	pi=3.142
	volume = pi * radius * radius * radius * 4/3
	return volume

radius1=30
volume1=calculate_volume_of_sphere(radius1)
print(f"The volume of sphere with radius {radius1} is: {volume1}")


radius2=40
volume2=calculate_volume_of_sphere(radius2)
print(f"The volume of sphere with radius {radius2} is: {volume2}")